name: foodgram_workflow

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements_for_test_code.txt
    - name: Test with flake8 and pytest
      run: |
        python -m flake8
        python -m pytest
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}

  build_and_push_to_docker_hub:
    name: Build and push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: tests
    if: github.ref == 'refs/heads/dev'
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./infra_dev/Dockerfile_dev
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/foodgram:latest

  send_message:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: [ tests, build_and_push_to_docker_hub ]
    steps:
      - name: send message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.workflow }} on branch ${{ github.ref_name }} finished!

            Job results:
            [tests]:  ${{ needs.tests.result }}
            [build_and_push_to_docker_hub]:  ${{ needs.build_and_push_to_docker_hub.result }}

            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
