name: foodgram_workflow

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements_for_test_code.txt
    - name: Test with flake8 and pytest
      run: |
        python -m flake8
        python -m pytest
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}

  send_message:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: [ tests ]
    steps:
      - name: send message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.workflow }} on branch ${{ github.ref_name }} finished!

            Job results:
            [tests]:  ${{ needs.tests.result }}

            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
